### ISSUE TITLE
Unable to install ruby `2.6.1p33`

### ISSUE THREAD

**Issue by meli-lewis** [cirlabs/amzn-injuries-app#1]
```bash
$ rbenv install 2.6.1p33
ruby-build: definition not found: 2.6.1p33

If the version you need is missing, try upgrading ruby-build:

  brew update && brew upgrade ruby-build
```

I ran `brew update && brew upgrade ruby-build`, but they were already up-to-date:

```bash
Warning: ruby-build 20200218 already installed
```

I'm going to proceed with the rest by installing `2.6.1` per se, and will comment on this issue with the results.

**Comment by kavyasukumar** [comment]
you should be good with 2.6.1 , the p33 build was a preview or hotfix build that i must have locked into. I was able to rebuild with 2.6.1. It might change the Gemfile.lock. If it does push it to the repo
