### ISSUE TITLE
Warning message for `bundle install`

### ISSUE THREAD

**Issue by meli-lewis** [cirlabs/amzn-injuries-app#2]
I'm noting this here to research later.

I'm running MacOS 10.14.5.

> The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32 java`.
>
> The dependency wdm (~> 0.1) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mswin32, x86-mingw32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mswin32 x86-mingw32`.

**Comment by kavyasukumar** [comment]
should be fixed with the new gem list
