### ISSUE TITLE
`bundle install` appears to fail because it relies on Kavya's GitHub authentication

### ISSUE THREAD

**Issue by meli-lewis** [cirlabs/amzn-injuries-app#3]
```
Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/kavyasukumar/middleman.git'
```

**Comment by kavyasukumar** [comment]
I am sorry.  

It was fixed in https://github.com/cirlabs/amzn-injuries-app/commit/0cae11c911a86c455dea3f035d56b9b48d103652. But looks like I never pushed the changes where the dependencies are removed. 

Please run

```sh
bundle clean
bundle install
bundle clean
```

> Two cleans are required to remove any stray old gems
