### ISSUE TITLE
ZIP code now reading in sidebar as undefined

### ISSUE THREAD

**Issue by meli-lewis** [cirlabs/amzn-injuries-app#4]
I assume this is a consequence of my redeployment (testing by just correcting one of the facility's city name).

I'm imagining there's a data type issue somewhere, but I can't identify it immediately; perhaps @kavyasukumar can?
<img width="269" alt="Screen Shot 2020-02-24 at 6 05 08 PM" src="https://user-images.githubusercontent.com/2907073/75208346-3ce66400-5730-11ea-8daf-d820fe05c7f4.png">

**Comment by meli-lewis** [comment]
I could see this being related because the zip code error seems like a problem the script is having accessing that attribute-value pair: When I run `bundle exec middleman build` I see these warnings.

`W, [2020-02-27T10:22:56.887736 #12582]  WARN -- : You are setting a key that conflicts with a built-in method Middleman::Util::EnhancedHash#max defined in Enumerable. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
W, [2020-02-27T10:22:56.888028 #12582]  WARN -- : You are setting a key that conflicts with a built-in method Middleman::Util::EnhancedHash#max defined in Enumerable. This can cause unexpected behavior when accessing the key as a property. You can still access the key via the #[] method.
`

**Comment by kavyasukumar** [comment]
There was a lingering bug from the rename. Fixed here https://github.com/cirlabs/amzn-injuries-app/commit/e7f99f410510a171ad437643bd76c14766938340
